/* Generated by Yosys 0.64+26 (git sha1 a54bca549, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

module \$paramod$75c960d2b8780f31b5b2a9710a4ae3f10fb177d0\data_processor (clk, rst_n, clk_gate_en, proc_idle, psel, penable, pwrite, paddr, pwdata, prdata, pready, pslverr, irq_in, irq_ack);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input clk_gate_en;
  wire clk_gate_en;
  output proc_idle;
  wire proc_idle;
  input psel;
  wire psel;
  input penable;
  wire penable;
  input pwrite;
  wire pwrite;
  input [7:0] paddr;
  wire [7:0] paddr;
  input [31:0] pwdata;
  wire [31:0] pwdata;
  output [31:0] prdata;
  reg [31:0] prdata;
  output pready;
  reg pready;
  output pslverr;
  reg pslverr;
  input irq_in;
  wire irq_in;
  output irq_ack;
  wire irq_ack;
  wire [31:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire [31:0] _004_;
  wire _005_;
  wire _006_;
  wire [31:0] _007_;
  wire [31:0] _008_;
  wire [31:0] _009_;
  wire [31:0] _010_;
  wire [31:0] _011_;
  wire [31:0] _012_;
  wire [31:0] _013_;
  wire [31:0] _014_;
  wire [31:0] _015_;
  wire [31:0] _016_;
  wire [2:0] _017_;
  wire [2:0] _018_;
  wire [31:0] _019_;
  wire [32:0] _020_;
  wire [31:0] _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire [31:0] _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire [31:0] _085_;
  wire _086_;
  wire [31:0] _087_;
  wire [31:0] _088_;
  wire [31:0] _089_;
  wire _090_;
  wire [31:0] _091_;
  wire [31:0] _092_;
  wire [31:0] _093_;
  wire _094_;
  wire [31:0] _095_;
  wire [31:0] _096_;
  wire [31:0] _097_;
  wire _098_;
  wire [31:0] _099_;
  wire [31:0] _100_;
  wire [31:0] _101_;
  wire _102_;
  wire [31:0] _103_;
  wire [31:0] _104_;
  wire [31:0] _105_;
  wire _106_;
  wire [31:0] _107_;
  wire [31:0] _108_;
  wire [31:0] _109_;
  wire _110_;
  wire [31:0] _111_;
  wire [31:0] _112_;
  wire [31:0] _113_;
  wire _114_;
  wire [31:0] _115_;
  wire [31:0] _116_;
  wire [31:0] _117_;
  wire _118_;
  wire [31:0] _119_;
  wire [31:0] _120_;
  wire [31:0] _121_;
  wire _122_;
  wire [31:0] _123_;
  wire [31:0] _124_;
  wire [31:0] _125_;
  wire _126_;
  wire [31:0] _127_;
  wire [31:0] _128_;
  wire [31:0] _129_;
  wire _130_;
  wire [31:0] _131_;
  wire [31:0] _132_;
  wire [31:0] _133_;
  wire _134_;
  wire [31:0] _135_;
  wire [31:0] _136_;
  wire [31:0] _137_;
  wire _138_;
  wire [31:0] _139_;
  wire [31:0] _140_;
  wire [31:0] _141_;
  wire _142_;
  wire [31:0] _143_;
  wire [31:0] _144_;
  wire [31:0] _145_;
  wire _146_;
  wire [31:0] _147_;
  wire [31:0] _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire [31:0] _175_;
  wire [31:0] _176_;
  wire [31:0] _177_;
  wire [31:0] _178_;
  wire [31:0] _179_;
  wire [32:0] _180_;
  wire [31:0] _181_;
  wire [31:0] _182_;
  wire [31:0] _183_;
  wire [31:0] alu_a;
  wire [31:0] alu_b;
  wire alu_overflow;
  wire [31:0] alu_result;
  wire clk_gated;
  reg [31:0] ctrl_reg;
  wire irq_en;
  reg irq_pending;
  wire [2:0] next_state;
  reg op_done;
  reg [31:0] op_reg;
  wire [3:0] opcode;
  reg [31:0] operand_a_reg;
  reg [31:0] operand_b_reg;
  reg overflow_flag;
  reg [2:0] pipe_rd_idx;
  reg [31:0] pipe_result;
  reg pipe_valid;
  wire [2:0] rd_idx;
  reg [31:0] \regfile[0] ;
  reg [31:0] \regfile[1] ;
  reg [31:0] \regfile[2] ;
  reg [31:0] \regfile[3] ;
  reg [31:0] \regfile[4] ;
  reg [31:0] \regfile[5] ;
  reg [31:0] \regfile[6] ;
  reg [31:0] \regfile[7] ;
  reg [31:0] result_reg;
  wire [2:0] rs1_idx;
  wire [2:0] rs2_idx;
  wire start_pulse;
  reg [2:0] state;
  assign _020_ = { 1'h0, alu_a } + { 1'h0, alu_b };
  assign _021_ = alu_a & alu_b;
  assign _005_ = psel & penable;
  assign clk_gated = clk & _074_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \regfile[7]  <= 32'd0;
    else if (_045_) \regfile[7]  <= _014_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \regfile[3]  <= 32'd0;
    else if (_046_) \regfile[3]  <= _010_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ctrl_reg[31:1] <= 31'h00000000;
    else if (_047_) ctrl_reg[31:1] <= pwdata[31:1];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ctrl_reg[0] <= 1'h0;
    else if (_030_) ctrl_reg[0] <= _000_[0];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \regfile[0]  <= 32'd0;
    else if (_048_) \regfile[0]  <= _007_;
  always @(posedge clk_gated, negedge rst_n)
    if (!rst_n) overflow_flag <= 1'h0;
    else if (_062_) overflow_flag <= alu_overflow;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) op_reg <= 32'd0;
    else if (_049_) op_reg <= pwdata;
  always @(posedge clk_gated, negedge rst_n)
    if (!rst_n) state <= 3'h0;
    else if (_033_) state <= next_state;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) operand_a_reg <= 32'd0;
    else if (_050_) operand_a_reg <= pwdata;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \regfile[5]  <= 32'd0;
    else if (_051_) \regfile[5]  <= _012_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \regfile[1]  <= 32'd0;
    else if (_052_) \regfile[1]  <= _008_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) operand_b_reg <= 32'd0;
    else if (_053_) operand_b_reg <= pwdata;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \regfile[4]  <= 32'd0;
    else if (_054_) \regfile[4]  <= _011_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \regfile[2]  <= 32'd0;
    else if (_055_) \regfile[2]  <= _009_;
  always @(posedge clk_gated, negedge rst_n)
    if (!rst_n) pipe_rd_idx <= 3'h0;
    else if (_062_) pipe_rd_idx <= op_reg[14:12];
  always @(posedge clk_gated, negedge rst_n)
    if (!rst_n) pipe_result <= 32'd0;
    else if (_062_) pipe_result <= alu_result;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) result_reg <= 32'd0;
    else if (_056_) result_reg <= pipe_result;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) \regfile[6]  <= 32'd0;
    else if (_057_) \regfile[6]  <= _013_;
  always @(posedge clk_gated, negedge rst_n)
    if (!rst_n) irq_pending <= 1'h0;
    else if (_044_) irq_pending <= _001_;
  assign _025_ = | { _086_, _067_ };
  assign _027_ = { _090_, _067_ } != 2'h1;
  assign _028_ = | { _118_, _067_ };
  assign _029_ = { _122_, _067_ } != 2'h1;
  assign _030_ = { _082_, _067_ } != 2'h1;
  assign _031_ = | { _142_, _067_ };
  assign _032_ = { _146_, _067_ } != 2'h1;
  assign _033_ = { proc_idle, irq_pending, ctrl_reg[0] } != 3'h4;
  assign _034_ = | { _102_, _067_ };
  assign _026_ = { _068_, _067_ } != 2'h1;
  assign _035_ = { _106_, _067_ } != 2'h1;
  assign _022_ = { _067_, _058_ } != 2'h3;
  assign _023_ = | { _067_, ctrl_reg[1] };
  assign _024_ = | { _069_, _067_ };
  assign _036_ = | { _134_, _067_ };
  assign _037_ = { _138_, _067_ } != 2'h1;
  assign _038_ = | { _110_, _067_ };
  assign _039_ = { _114_, _067_ } != 2'h1;
  assign _040_ = | { _126_, _067_ };
  assign _041_ = { _130_, _067_ } != 2'h1;
  assign _042_ = | { _094_, _067_ };
  assign _043_ = { _098_, _067_ } != 2'h1;
  assign _044_ = | { _063_, _065_ };
  assign _045_ = & { _022_, _023_, _024_, _025_, _026_, _027_ };
  assign _046_ = & { _022_, _023_, _024_, _026_, _028_, _029_ };
  assign _047_ = & { _082_, _067_ };
  assign _048_ = & { _022_, _023_, _024_, _026_, _031_, _032_ };
  assign _049_ = & { _079_, _067_ };
  assign _050_ = & { _078_, _067_ };
  assign _051_ = & { _022_, _023_, _024_, _026_, _034_, _035_ };
  assign _052_ = & { _022_, _023_, _024_, _026_, _036_, _037_ };
  assign _053_ = & { _077_, _067_ };
  assign _054_ = & { _022_, _023_, _024_, _026_, _038_, _039_ };
  assign _055_ = & { _022_, _023_, _024_, _026_, _040_, _041_ };
  assign _056_ = & { _069_, _060_ };
  assign _057_ = & { _022_, _023_, _024_, _026_, _042_, _043_ };
  assign _060_ = ~ _067_;
  assign _059_ = | { _083_, _082_, _079_, _078_, _077_, _076_ };
  assign _058_ = | { _082_, _079_, _078_, _077_ };
  assign _061_ = alu_a == alu_b;
  assign _002_ = state == 3'h3;
  assign _064_ = paddr >= 8'h18;
  assign _065_ = irq_in && ctrl_reg[2];
  assign _067_ = _066_ && pwrite;
  assign _069_ = pipe_valid && _002_;
  assign _066_ = psel && penable;
  assign _070_ = _066_ && _071_;
  assign _068_ = _064_ && _072_;
  assign _071_ = ! pwrite;
  assign _072_ = paddr < 32'd56;
  assign _073_ = | state;
  assign _074_ = ~ clk_gate_en;
  assign _075_ = alu_a | alu_b;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) prdata <= 32'd0;
    else prdata <= _004_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) pready <= 1'h0;
    else pready <= _005_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) pslverr <= 1'h0;
    else pslverr <= _006_;
  always @(posedge clk_gated, negedge rst_n)
    if (!rst_n) op_done <= 1'h0;
    else op_done <= _002_;
  always @(posedge clk_gated, negedge rst_n)
    if (!rst_n) pipe_valid <= 1'h0;
    else pipe_valid <= _003_;
  assign _004_ = _070_ ? _176_ : 32'd0;
  assign _080_ = _068_ ? 1'h0 : 1'h1;
  assign _081_ = _059_ ? 1'h0 : _080_;
  assign _083_ = paddr == 8'h10;
  assign _076_ = paddr == 8'h0c;
  assign _006_ = _070_ ? _081_ : 1'h0;
  assign _084_ = _082_ ? pwdata[0] : 1'hx;
  assign _000_[0] = _067_ ? _084_ : 1'h0;
  assign _085_ = _086_ ? pipe_result : 32'hxxxxxxxx;
  assign _086_ = pipe_rd_idx == 3'h7;
  assign _087_ = ctrl_reg[1] ? _085_ : 32'hxxxxxxxx;
  assign _088_ = _069_ ? _087_ : 32'hxxxxxxxx;
  assign _089_ = _090_ ? pwdata : 32'hxxxxxxxx;
  assign _090_ = _179_[2:0] == 3'h7;
  assign _091_ = _068_ ? _089_ : 32'hxxxxxxxx;
  assign _092_ = _058_ ? 32'hxxxxxxxx : _091_;
  assign _014_ = _067_ ? _092_ : _088_;
  assign _093_ = _094_ ? pipe_result : 32'hxxxxxxxx;
  assign _094_ = pipe_rd_idx == 3'h6;
  assign _095_ = ctrl_reg[1] ? _093_ : 32'hxxxxxxxx;
  assign _096_ = _069_ ? _095_ : 32'hxxxxxxxx;
  assign _097_ = _098_ ? pwdata : 32'hxxxxxxxx;
  assign _098_ = _179_[2:0] == 3'h6;
  assign _099_ = _068_ ? _097_ : 32'hxxxxxxxx;
  assign _100_ = _058_ ? 32'hxxxxxxxx : _099_;
  assign _013_ = _067_ ? _100_ : _096_;
  assign _101_ = _102_ ? pipe_result : 32'hxxxxxxxx;
  assign _102_ = pipe_rd_idx == 3'h5;
  assign _103_ = ctrl_reg[1] ? _101_ : 32'hxxxxxxxx;
  assign _104_ = _069_ ? _103_ : 32'hxxxxxxxx;
  assign _105_ = _106_ ? pwdata : 32'hxxxxxxxx;
  assign _106_ = _179_[2:0] == 3'h5;
  assign _107_ = _068_ ? _105_ : 32'hxxxxxxxx;
  assign _108_ = _058_ ? 32'hxxxxxxxx : _107_;
  assign _012_ = _067_ ? _108_ : _104_;
  assign _109_ = _110_ ? pipe_result : 32'hxxxxxxxx;
  assign _110_ = pipe_rd_idx == 3'h4;
  assign _111_ = ctrl_reg[1] ? _109_ : 32'hxxxxxxxx;
  assign _112_ = _069_ ? _111_ : 32'hxxxxxxxx;
  assign _113_ = _114_ ? pwdata : 32'hxxxxxxxx;
  assign _114_ = _179_[2:0] == 3'h4;
  assign _115_ = _068_ ? _113_ : 32'hxxxxxxxx;
  assign _116_ = _058_ ? 32'hxxxxxxxx : _115_;
  assign _011_ = _067_ ? _116_ : _112_;
  assign _117_ = _118_ ? pipe_result : 32'hxxxxxxxx;
  assign _118_ = pipe_rd_idx == 3'h3;
  assign _119_ = ctrl_reg[1] ? _117_ : 32'hxxxxxxxx;
  assign _120_ = _069_ ? _119_ : 32'hxxxxxxxx;
  assign _121_ = _122_ ? pwdata : 32'hxxxxxxxx;
  assign _122_ = _179_[2:0] == 3'h3;
  assign _123_ = _068_ ? _121_ : 32'hxxxxxxxx;
  assign _124_ = _058_ ? 32'hxxxxxxxx : _123_;
  assign _010_ = _067_ ? _124_ : _120_;
  assign _125_ = _126_ ? pipe_result : 32'hxxxxxxxx;
  assign _126_ = pipe_rd_idx == 3'h2;
  assign _127_ = ctrl_reg[1] ? _125_ : 32'hxxxxxxxx;
  assign _128_ = _069_ ? _127_ : 32'hxxxxxxxx;
  assign _129_ = _130_ ? pwdata : 32'hxxxxxxxx;
  assign _130_ = _179_[2:0] == 3'h2;
  assign _131_ = _068_ ? _129_ : 32'hxxxxxxxx;
  assign _132_ = _058_ ? 32'hxxxxxxxx : _131_;
  assign _009_ = _067_ ? _132_ : _128_;
  assign _133_ = _134_ ? pipe_result : 32'hxxxxxxxx;
  assign _134_ = pipe_rd_idx == 3'h1;
  assign _135_ = ctrl_reg[1] ? _133_ : 32'hxxxxxxxx;
  assign _136_ = _069_ ? _135_ : 32'hxxxxxxxx;
  assign _137_ = _138_ ? pwdata : 32'hxxxxxxxx;
  assign _139_ = _068_ ? _137_ : 32'hxxxxxxxx;
  assign _140_ = _058_ ? 32'hxxxxxxxx : _139_;
  assign _008_ = _067_ ? _140_ : _136_;
  assign _141_ = _142_ ? pipe_result : 32'hxxxxxxxx;
  assign _142_ = ! pipe_rd_idx;
  assign _143_ = ctrl_reg[1] ? _141_ : 32'hxxxxxxxx;
  assign _144_ = _069_ ? _143_ : 32'hxxxxxxxx;
  assign _145_ = _146_ ? pwdata : 32'hxxxxxxxx;
  assign _147_ = _068_ ? _145_ : 32'hxxxxxxxx;
  assign _148_ = _058_ ? 32'hxxxxxxxx : _147_;
  assign _007_ = _067_ ? _148_ : _144_;
  assign _082_ = paddr == 8'h14;
  assign _077_ = paddr == 8'h08;
  assign _078_ = paddr == 8'h04;
  assign _079_ = ! paddr;
  assign _018_ = ctrl_reg[0] ? 3'h1 : 3'hx;
  assign _017_ = irq_pending ? 3'h4 : _018_;
  function [2:0] _349_;
    input [2:0] a;
    input [8:0] b;
    input [2:0] s;
    casez (s) // synopsys parallel_case
      3'b??1:
        _349_ = b[2:0];
      3'b?1?:
        _349_ = b[5:3];
      3'b1??:
        _349_ = b[8:6];
      default:
        _349_ = a;
    endcase
  endfunction
  assign next_state = _349_(3'h0, { _017_, 6'h13 }, { proc_idle, _149_, _062_ });
  assign _062_ = state == 3'h2;
  assign _149_ = state == 3'h1;
  assign proc_idle = ! state;
  assign irq_ack = _063_ ? 1'h1 : 1'h0;
  assign _063_ = state == 3'h4;
  assign _150_ = _063_ ? 1'h0 : 1'hx;
  assign _001_ = _065_ ? 1'h1 : _150_;
  assign _003_ = _062_ ? 1'h1 : 1'h0;
  function [0:0] _358_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _358_ = b[0:0];
      2'b1?:
        _358_ = b[1:1];
      default:
        _358_ = a;
    endcase
  endfunction
  assign alu_overflow = _358_(1'h0, { _020_[32], _180_[32] }, { _152_, _151_ });
  function [31:0] _359_;
    input [31:0] a;
    input [255:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _359_ = b[31:0];
      8'b??????1?:
        _359_ = b[63:32];
      8'b?????1??:
        _359_ = b[95:64];
      8'b????1???:
        _359_ = b[127:96];
      8'b???1????:
        _359_ = b[159:128];
      8'b??1?????:
        _359_ = b[191:160];
      8'b?1??????:
        _359_ = b[223:192];
      8'b1???????:
        _359_ = b[255:224];
      default:
        _359_ = a;
    endcase
  endfunction
  assign alu_result = _359_(32'd0, { _020_[31:0], _180_[31:0], _021_, _075_, _183_, _177_, _178_, _182_ }, { _152_, _151_, _158_, _157_, _156_, _155_, _154_, _153_ });
  assign _153_ = op_reg[3:0] == 4'h7;
  assign _154_ = op_reg[3:0] == 4'h6;
  assign _155_ = op_reg[3:0] == 4'h5;
  assign _156_ = op_reg[3:0] == 4'h4;
  assign _157_ = op_reg[3:0] == 4'h3;
  assign _158_ = op_reg[3:0] == 4'h2;
  assign _151_ = op_reg[3:0] == 4'h1;
  assign _152_ = ! op_reg[3:0];
  function [31:0] _368_;
    input [31:0] a;
    input [255:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _368_ = b[31:0];
      8'b??????1?:
        _368_ = b[63:32];
      8'b?????1??:
        _368_ = b[95:64];
      8'b????1???:
        _368_ = b[127:96];
      8'b???1????:
        _368_ = b[159:128];
      8'b??1?????:
        _368_ = b[191:160];
      8'b?1??????:
        _368_ = b[223:192];
      8'b1???????:
        _368_ = b[255:224];
      default:
        _368_ = a;
    endcase
  endfunction
  assign _016_ = _368_(32'hxxxxxxxx, { \regfile[0] , \regfile[1] , \regfile[2] , \regfile[3] , \regfile[4] , \regfile[5] , \regfile[6] , \regfile[7]  }, { _166_, _165_, _164_, _163_, _162_, _161_, _160_, _159_ });
  assign _159_ = op_reg[10:8] == 3'h7;
  assign _160_ = op_reg[10:8] == 3'h6;
  assign _161_ = op_reg[10:8] == 3'h5;
  assign _162_ = op_reg[10:8] == 3'h4;
  assign _163_ = op_reg[10:8] == 3'h3;
  assign _164_ = op_reg[10:8] == 3'h2;
  assign _165_ = op_reg[10:8] == 3'h1;
  assign _166_ = ! op_reg[10:8];
  function [31:0] _377_;
    input [31:0] a;
    input [255:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _377_ = b[31:0];
      8'b??????1?:
        _377_ = b[63:32];
      8'b?????1??:
        _377_ = b[95:64];
      8'b????1???:
        _377_ = b[127:96];
      8'b???1????:
        _377_ = b[159:128];
      8'b??1?????:
        _377_ = b[191:160];
      8'b?1??????:
        _377_ = b[223:192];
      8'b1???????:
        _377_ = b[255:224];
      default:
        _377_ = a;
    endcase
  endfunction
  assign _015_ = _377_(32'hxxxxxxxx, { \regfile[0] , \regfile[1] , \regfile[2] , \regfile[3] , \regfile[4] , \regfile[5] , \regfile[6] , \regfile[7]  }, { _174_, _173_, _172_, _171_, _170_, _169_, _168_, _167_ });
  assign _167_ = op_reg[6:4] == 3'h7;
  assign _168_ = op_reg[6:4] == 3'h6;
  assign _169_ = op_reg[6:4] == 3'h5;
  assign _170_ = op_reg[6:4] == 3'h4;
  assign _171_ = op_reg[6:4] == 3'h3;
  assign _172_ = op_reg[6:4] == 3'h2;
  assign _173_ = op_reg[6:4] == 3'h1;
  assign _174_ = ! op_reg[6:4];
  assign alu_b = ctrl_reg[1] ? _016_ : operand_b_reg;
  assign alu_a = ctrl_reg[1] ? _015_ : operand_a_reg;
  function [31:0] _388_;
    input [31:0] a;
    input [255:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _388_ = b[31:0];
      8'b??????1?:
        _388_ = b[63:32];
      8'b?????1??:
        _388_ = b[95:64];
      8'b????1???:
        _388_ = b[127:96];
      8'b???1????:
        _388_ = b[159:128];
      8'b??1?????:
        _388_ = b[191:160];
      8'b?1??????:
        _388_ = b[223:192];
      8'b1???????:
        _388_ = b[255:224];
      default:
        _388_ = a;
    endcase
  endfunction
  assign _019_ = _388_(32'hxxxxxxxx, { \regfile[0] , \regfile[1] , \regfile[2] , \regfile[3] , \regfile[4] , \regfile[5] , \regfile[6] , \regfile[7]  }, { _146_, _138_, _130_, _122_, _114_, _106_, _098_, _090_ });
  assign _138_ = _179_[2:0] == 3'h1;
  assign _146_ = ! _179_[2:0];
  assign _175_ = _068_ ? _019_ : 32'd3735928559;
  function [31:0] _392_;
    input [31:0] a;
    input [191:0] b;
    input [5:0] s;
    casez (s) // synopsys parallel_case
      6'b?????1:
        _392_ = b[31:0];
      6'b????1?:
        _392_ = b[63:32];
      6'b???1??:
        _392_ = b[95:64];
      6'b??1???:
        _392_ = b[127:96];
      6'b?1????:
        _392_ = b[159:128];
      6'b1?????:
        _392_ = b[191:160];
      default:
        _392_ = a;
    endcase
  endfunction
  assign _176_ = _392_(_175_, { op_reg, operand_a_reg, operand_b_reg, result_reg, 28'h0000000, irq_pending, overflow_flag, _073_, op_done, ctrl_reg }, { _079_, _078_, _077_, _076_, _083_, _082_ });
  assign _177_ = alu_a << alu_b[4:0];
  assign _178_ = alu_a >> alu_b[4:0];
  assign _180_ = { 1'h0, alu_a } - { 1'h0, alu_b };
  assign { _179_[29:0], _181_[1:0] } = paddr - 8'h18;
  assign _182_ = _061_ ? 32'd1 : 32'd0;
  assign _183_ = alu_a ^ alu_b;
  assign _179_[31:30] = 2'h0;
  assign _181_[31:2] = _179_[29:0];
  assign start_pulse = ctrl_reg[0];
  assign irq_en = ctrl_reg[2];
  assign rd_idx = op_reg[14:12];
  assign rs2_idx = op_reg[10:8];
  assign rs1_idx = op_reg[6:4];
  assign opcode = op_reg[3:0];
endmodule

module \$paramod$aa0e0fe2fcccd29e4fd4c43da721521782bc64cd\pmu_fsm (clk, rst_n, sleep_req, proc_idle, mem_idle, wakeup_req, seq_sleep_cmd, seq_wakeup_cmd, seq_sleep_ack, seq_wakeup_ack, thermal_alert, battery_low, fault_in, pmu_active, pmu_sleeping, pmu_fault, pmu_state_out);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input sleep_req;
  wire sleep_req;
  input proc_idle;
  wire proc_idle;
  input mem_idle;
  wire mem_idle;
  input wakeup_req;
  wire wakeup_req;
  output seq_sleep_cmd;
  wire seq_sleep_cmd;
  output seq_wakeup_cmd;
  wire seq_wakeup_cmd;
  input seq_sleep_ack;
  wire seq_sleep_ack;
  input seq_wakeup_ack;
  wire seq_wakeup_ack;
  input thermal_alert;
  wire thermal_alert;
  input battery_low;
  wire battery_low;
  input fault_in;
  wire fault_in;
  output pmu_active;
  wire pmu_active;
  output pmu_sleeping;
  wire pmu_sleeping;
  output pmu_fault;
  wire pmu_fault;
  output [3:0] pmu_state_out;
  wire [3:0] pmu_state_out;
  wire [7:0] _00_;
  wire [15:0] _01_;
  wire [3:0] _02_;
  wire [3:0] _03_;
  wire [3:0] _04_;
  wire [3:0] _05_;
  wire _06_;
  wire [3:0] _07_;
  wire [3:0] _08_;
  wire [3:0] _09_;
  wire [3:0] _10_;
  wire [3:0] _11_;
  wire [3:0] _12_;
  wire [3:0] _13_;
  wire [15:0] _14_;
  wire [7:0] _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire [3:0] _35_;
  reg [7:0] boot_cnt;
  wire boot_done;
  wire [3:0] next_state;
  reg [3:0] state;
  reg [15:0] timeout_cnt;
  wire timeout_en;
  wire timeout_hit;
  assign _14_ = timeout_cnt + 1'h1;
  assign _15_ = boot_cnt + 1'h1;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state <= 4'h0;
    else if (_22_) state <= next_state;
  assign _16_ = { _23_, battery_low, wakeup_req } != 3'h4;
  assign _17_ = { _32_, timeout_hit, seq_sleep_ack } != 3'h4;
  assign _18_ = { _31_, seq_wakeup_ack } != 2'h2;
  assign _19_ = { pmu_active, _30_, _27_, battery_low } != 4'h8;
  assign _20_ = { _25_, boot_done } != 2'h2;
  assign _21_ = { _24_, _28_ } != 2'h2;
  assign _22_ = & { _16_, _17_, _18_, _19_, _20_, _21_ };
  assign pmu_fault = state == 4'h8;
  assign timeout_hit = timeout_cnt >= 16'h03e8;
  assign boot_done = boot_cnt >= 8'h0f;
  assign _26_ = sleep_req && proc_idle;
  assign _27_ = _26_ && mem_idle;
  assign _28_ = wakeup_req && _29_;
  assign _29_ = ! battery_low;
  assign _30_ = fault_in || thermal_alert;
  assign pmu_sleeping = _23_ || _24_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) boot_cnt <= 8'h00;
    else boot_cnt <= _00_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) timeout_cnt <= 16'h0000;
    else timeout_cnt <= _01_;
  assign _04_ = seq_wakeup_ack ? 4'h2 : 4'hx;
  assign _03_ = _28_ ? 4'h7 : 4'hx;
  assign _02_ = battery_low ? 4'h6 : 4'hx;
  assign _13_ = wakeup_req ? 4'h7 : _02_;
  assign _12_ = seq_sleep_ack ? _35_ : 4'hx;
  assign _11_ = timeout_hit ? 4'h8 : _12_;
  assign _10_ = _30_ ? 4'h8 : 4'h4;
  assign _06_ = _30_ ? 1'h0 : 1'h1;
  assign _09_ = _27_ ? 4'h3 : 4'hx;
  assign _08_ = battery_low ? 4'h3 : _09_;
  assign _07_ = _30_ ? 4'h8 : _08_;
  assign _05_ = boot_done ? 4'h2 : 4'hx;
  function [3:0] _69_;
    input [3:0] a;
    input [31:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _69_ = b[3:0];
      8'b??????1?:
        _69_ = b[7:4];
      8'b?????1??:
        _69_ = b[11:8];
      8'b????1???:
        _69_ = b[15:12];
      8'b???1????:
        _69_ = b[19:16];
      8'b??1?????:
        _69_ = b[23:20];
      8'b?1??????:
        _69_ = b[27:24];
      8'b1???????:
        _69_ = b[31:28];
      default:
        _69_ = a;
    endcase
  endfunction
  assign next_state = _69_(4'h8, { 4'h1, _05_, _07_, _10_, _11_, _13_, _03_, _04_ }, { _34_, _25_, pmu_active, _33_, _32_, _23_, _24_, _31_ });
  assign _24_ = state == 4'h6;
  assign _23_ = state == 4'h5;
  assign pmu_active = state == 4'h2;
  assign _25_ = state == 4'h1;
  assign _34_ = ! state;
  assign timeout_en = _32_ ? 1'h1 : 1'h0;
  assign seq_wakeup_cmd = _31_ ? 1'h1 : 1'h0;
  assign _31_ = state == 4'h7;
  function [0:0] _78_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _78_ = b[0:0];
      2'b1?:
        _78_ = b[1:1];
      default:
        _78_ = a;
    endcase
  endfunction
  assign seq_sleep_cmd = _78_(1'h0, { _06_, 1'h1 }, { _33_, _32_ });
  assign _32_ = state == 4'h4;
  assign _33_ = state == 4'h3;
  assign _00_ = _25_ ? _15_ : 8'h00;
  assign _01_ = timeout_en ? _14_ : 16'h0000;
  assign _35_ = battery_low ? 4'h6 : 4'h5;
  assign pmu_state_out = state;
endmodule

module icg_cell(clk_in, enable, test_en, clk_out);
  input clk_in;
  wire clk_in;
  input enable;
  wire enable;
  input test_en;
  wire test_en;
  output clk_out;
  wire clk_out;
  wire _0_;
  assign clk_out = clk_in & _0_;
  assign _0_ = enable | test_en;
endmodule

module iso_cell(data_in, iso_en, data_out);
  input data_in;
  wire data_in;
  input iso_en;
  wire iso_en;
  output data_out;
  wire data_out;
  assign data_out = iso_en ? 1'h0 : data_in;
endmodule

module power_sequencer(clk, rst_n, seq_sleep_cmd, seq_wakeup_cmd, seq_sleep_ack, seq_wakeup_ack, ret_save_en, ret_restore_en, ret_save_done, ret_restore_done, clk_gate_en, iso_en, pwr_sw_off, lvl_shift_en);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input seq_sleep_cmd;
  wire seq_sleep_cmd;
  input seq_wakeup_cmd;
  wire seq_wakeup_cmd;
  output seq_sleep_ack;
  wire seq_sleep_ack;
  output seq_wakeup_ack;
  wire seq_wakeup_ack;
  output ret_save_en;
  wire ret_save_en;
  output ret_restore_en;
  wire ret_restore_en;
  input ret_save_done;
  wire ret_save_done;
  input ret_restore_done;
  wire ret_restore_done;
  output clk_gate_en;
  wire clk_gate_en;
  output iso_en;
  wire iso_en;
  output pwr_sw_off;
  wire pwr_sw_off;
  output lvl_shift_en;
  wire lvl_shift_en;
  wire [3:0] _00_;
  wire [3:0] _01_;
  wire [3:0] _02_;
  wire [3:0] _03_;
  wire [3:0] _04_;
  wire [3:0] _05_;
  wire [3:0] _06_;
  wire [3:0] _07_;
  wire [3:0] _08_;
  wire [3:0] _09_;
  wire [3:0] _10_;
  wire [3:0] _11_;
  wire [3:0] _12_;
  wire [3:0] _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  wire _36_;
  wire _37_;
  wire _38_;
  wire _39_;
  wire _40_;
  wire [3:0] next_state;
  reg [3:0] state;
  reg [3:0] step_cnt;
  wire step_cnt_en;
  wire step_done;
  assign _13_ = step_cnt + 1'h1;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state <= 4'h0;
    else if (_25_) state <= next_state;
  assign _14_ = { _40_, seq_wakeup_cmd, seq_sleep_cmd } != 3'h4;
  assign _15_ = { _35_, seq_sleep_cmd } != 2'h3;
  assign _16_ = { _30_, seq_wakeup_cmd } != 2'h3;
  assign _17_ = { _37_, ret_save_done } != 2'h2;
  assign _18_ = { _33_, ret_restore_done } != 2'h2;
  assign _19_ = { _31_, step_done } != 2'h2;
  assign _20_ = { _32_, step_done } != 2'h2;
  assign _21_ = { _39_, step_done } != 2'h2;
  assign _22_ = { _34_, step_done } != 2'h2;
  assign _23_ = { _36_, step_done } != 2'h2;
  assign _24_ = { _38_, step_done } != 2'h2;
  assign _25_ = & { _14_, _15_, _16_, _17_, _18_, _19_, _20_, _21_, _22_, _23_, _24_ };
  assign _26_ = | { _38_, _37_, _36_, _35_, _34_, _33_ };
  assign _27_ = | { _36_, _35_ };
  assign _28_ = | { _39_, _38_, _36_, _34_, _32_, _31_ };
  assign _29_ = | { _39_, _38_, _37_, _36_, _35_, _34_, _33_, _32_ };
  assign step_done = step_cnt >= 4'h8;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) step_cnt <= 4'h0;
    else step_cnt <= _00_;
  assign _04_ = seq_wakeup_cmd ? 4'hx : 4'h0;
  assign _03_ = step_done ? 4'ha : 4'hx;
  assign _02_ = step_done ? 4'h9 : 4'hx;
  assign _01_ = ret_restore_done ? 4'h8 : 4'hx;
  assign _12_ = step_done ? 4'h7 : 4'hx;
  assign _11_ = seq_sleep_cmd ? 4'hx : 4'h0;
  assign _10_ = step_done ? 4'h5 : 4'hx;
  assign _09_ = ret_save_done ? 4'h4 : 4'hx;
  assign _08_ = step_done ? 4'h3 : 4'hx;
  assign _07_ = step_done ? 4'h2 : 4'hx;
  assign _06_ = seq_wakeup_cmd ? 4'h6 : 4'hx;
  assign _05_ = seq_sleep_cmd ? 4'h1 : _06_;
  function [3:0] _73_;
    input [3:0] a;
    input [43:0] b;
    input [10:0] s;
    casez (s) // synopsys parallel_case
      11'b??????????1:
        _73_ = b[3:0];
      11'b?????????1?:
        _73_ = b[7:4];
      11'b????????1??:
        _73_ = b[11:8];
      11'b???????1???:
        _73_ = b[15:12];
      11'b??????1????:
        _73_ = b[19:16];
      11'b?????1?????:
        _73_ = b[23:20];
      11'b????1??????:
        _73_ = b[27:24];
      11'b???1???????:
        _73_ = b[31:28];
      11'b??1????????:
        _73_ = b[35:32];
      11'b?1?????????:
        _73_ = b[39:36];
      11'b1??????????:
        _73_ = b[43:40];
      default:
        _73_ = a;
    endcase
  endfunction
  assign next_state = _73_(4'h0, { _05_, _07_, _08_, _09_, _10_, _11_, _12_, _01_, _02_, _03_, _04_ }, { _40_, _39_, _38_, _37_, _36_, _35_, _34_, _33_, _32_, _31_, _30_ });
  assign _40_ = ! state;
  assign step_cnt_en = _28_ ? 1'h1 : 1'h0;
  assign _31_ = state == 4'h9;
  assign pwr_sw_off = _27_ ? 1'h1 : 1'h0;
  assign clk_gate_en = _29_ ? 1'h1 : 1'h0;
  assign _32_ = state == 4'h8;
  assign _39_ = state == 4'h1;
  assign ret_restore_en = _33_ ? 1'h1 : 1'h0;
  assign ret_save_en = _37_ ? 1'h1 : 1'h0;
  assign seq_wakeup_ack = _30_ ? 1'h1 : 1'h0;
  assign _30_ = state == 4'ha;
  assign seq_sleep_ack = _35_ ? 1'h1 : 1'h0;
  assign iso_en = _26_ ? 1'h1 : 1'h0;
  assign _33_ = state == 4'h7;
  assign _34_ = state == 4'h6;
  assign _35_ = state == 4'h5;
  assign _36_ = state == 4'h4;
  assign _37_ = state == 4'h3;
  assign _38_ = state == 4'h2;
  assign _00_ = step_cnt_en ? _13_ : 4'h0;
  assign lvl_shift_en = 1'h1;
endmodule

module retention_ctrl(clk, rst_n, ret_save_en, ret_restore_en, ret_save_done, ret_restore_done, context_saved, context_valid);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input ret_save_en;
  wire ret_save_en;
  input ret_restore_en;
  wire ret_restore_en;
  output ret_save_done;
  reg ret_save_done;
  output ret_restore_done;
  reg ret_restore_done;
  output context_saved;
  reg context_saved;
  output context_valid;
  wire context_valid;
  wire [3:0] _00_;
  wire [2:0] _01_;
  wire [2:0] _02_;
  wire [2:0] _03_;
  wire [2:0] _04_;
  wire [2:0] _05_;
  wire [2:0] _06_;
  wire [3:0] _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire ctx_saved_next;
  wire ctx_valid_next;
  wire [2:0] next_state;
  reg [3:0] op_cnt;
  wire op_cnt_en;
  wire restore_complete;
  wire restore_done_next;
  wire save_complete;
  wire save_done_next;
  reg [2:0] state;
  assign _07_ = op_cnt + 1'h1;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) state <= 3'h0;
    else if (_13_) state <= next_state;
  assign _08_ = { _20_, ret_restore_en, ret_save_en } != 3'h4;
  assign _09_ = { _18_, ret_save_en } != 2'h3;
  assign _10_ = { _16_, ret_restore_en } != 2'h3;
  assign _11_ = { _17_, restore_complete } != 2'h2;
  assign _12_ = { _19_, restore_complete } != 2'h2;
  assign _13_ = & { _08_, _09_, _10_, _11_, _12_ };
  assign _14_ = | { _18_, _17_ };
  assign _15_ = | { _19_, _17_ };
  assign restore_complete = op_cnt >= 4'h4;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ret_save_done <= 1'h0;
    else ret_save_done <= save_done_next;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ret_restore_done <= 1'h0;
    else ret_restore_done <= ctx_valid_next;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) context_saved <= 1'h0;
    else context_saved <= ctx_saved_next;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) op_cnt <= 4'h0;
    else op_cnt <= _00_;
  assign _06_ = ret_restore_en ? 3'hx : 3'h0;
  assign _05_ = restore_complete ? 3'h4 : 3'hx;
  assign _04_ = ret_save_en ? 3'hx : 3'h0;
  assign _03_ = restore_complete ? 3'h2 : 3'hx;
  assign _02_ = ret_restore_en ? 3'h3 : 3'hx;
  assign _01_ = ret_save_en ? 3'h1 : _02_;
  function [2:0] _42_;
    input [2:0] a;
    input [14:0] b;
    input [4:0] s;
    casez (s) // synopsys parallel_case
      5'b????1:
        _42_ = b[2:0];
      5'b???1?:
        _42_ = b[5:3];
      5'b??1??:
        _42_ = b[8:6];
      5'b?1???:
        _42_ = b[11:9];
      5'b1????:
        _42_ = b[14:12];
      default:
        _42_ = a;
    endcase
  endfunction
  assign next_state = _42_(3'h0, { _01_, _03_, _04_, _05_, _06_ }, { _20_, _19_, _18_, _17_, _16_ });
  assign _20_ = ! state;
  assign ctx_valid_next = _16_ ? 1'h1 : 1'h0;
  assign ctx_saved_next = _14_ ? 1'h1 : 1'h0;
  assign _16_ = state == 3'h4;
  assign save_done_next = _18_ ? 1'h1 : 1'h0;
  assign _18_ = state == 3'h2;
  assign op_cnt_en = _15_ ? 1'h1 : 1'h0;
  assign _17_ = state == 3'h3;
  assign _19_ = state == 3'h1;
  assign _00_ = op_cnt_en ? _07_ : 4'h0;
  assign restore_done_next = ctx_valid_next;
  assign save_complete = restore_complete;
  assign context_valid = ret_restore_done;
endmodule

module sensor_regbank(clk, rst_n, reg_wr_en, reg_rd_en, reg_addr, reg_wdata, reg_rdata, reg_ack, sensor0_data, sensor1_data, sensor2_data, irq_out, pwr_ctrl_sleep_req, pwr_ctrl_mode);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input reg_wr_en;
  wire reg_wr_en;
  input reg_rd_en;
  wire reg_rd_en;
  input [7:0] reg_addr;
  wire [7:0] reg_addr;
  input [31:0] reg_wdata;
  wire [31:0] reg_wdata;
  output [31:0] reg_rdata;
  reg [31:0] reg_rdata;
  output reg_ack;
  reg reg_ack;
  input [31:0] sensor0_data;
  wire [31:0] sensor0_data;
  input [31:0] sensor1_data;
  wire [31:0] sensor1_data;
  input [31:0] sensor2_data;
  wire [31:0] sensor2_data;
  output irq_out;
  wire irq_out;
  output pwr_ctrl_sleep_req;
  wire pwr_ctrl_sleep_req;
  output [1:0] pwr_ctrl_mode;
  wire [1:0] pwr_ctrl_mode;
  wire [31:0] _00_;
  wire _01_;
  wire [31:0] _02_;
  wire [2:0] _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire [31:0] _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  reg [31:0] ctrl_reg;
  reg [31:0] irq_mask_reg;
  wire irq_sensor0;
  wire irq_sensor1;
  wire irq_sensor2;
  wire [31:0] irq_status_reg;
  reg [31:0] irq_thresh0_reg;
  reg [31:0] irq_thresh1_reg;
  reg [31:0] irq_thresh2_reg;
  reg [31:0] pwr_ctrl_reg;
  reg sensor_valid;
  assign _03_ = irq_status_reg[2:0] & irq_mask_reg[2:0];
  assign irq_out = _29_ & ctrl_reg[9];
  always @(posedge clk, negedge rst_n)
    if (!rst_n) irq_thresh2_reg <= 32'd4294967295;
    else if (_04_) irq_thresh2_reg <= reg_wdata;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) irq_thresh1_reg <= 32'd4294967295;
    else if (_05_) irq_thresh1_reg <= reg_wdata;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) irq_thresh0_reg <= 32'd4294967295;
    else if (_06_) irq_thresh0_reg <= reg_wdata;
  reg [2:0] _35_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) _35_ <= 3'h0;
    else _35_ <= _00_[2:0];
  assign irq_status_reg[2:0] = _35_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ctrl_reg <= 32'd0;
    else if (_07_) ctrl_reg <= reg_wdata;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) pwr_ctrl_reg <= 32'd0;
    else if (_08_) pwr_ctrl_reg <= reg_wdata;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) irq_mask_reg <= 32'd0;
    else if (_09_) irq_mask_reg <= reg_wdata;
  assign _04_ = & { _14_, reg_wr_en };
  assign _05_ = & { _15_, reg_wr_en };
  assign _06_ = & { _16_, reg_wr_en };
  assign _07_ = & { _22_, reg_wr_en };
  assign _08_ = & { _13_, reg_wr_en };
  assign _09_ = & { _17_, reg_wr_en };
  assign irq_sensor0 = sensor0_data > irq_thresh0_reg;
  assign irq_sensor1 = sensor1_data > irq_thresh1_reg;
  assign irq_sensor2 = sensor2_data > irq_thresh2_reg;
  assign _11_ = reg_wr_en && _10_;
  assign _01_ = reg_rd_en | reg_wr_en;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_rdata <= 32'd0;
    else reg_rdata <= _02_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) reg_ack <= 1'h0;
    else reg_ack <= _01_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) sensor_valid <= 1'h0;
    else sensor_valid <= 1'h1;
  function [31:0] _53_;
    input [31:0] a;
    input [351:0] b;
    input [10:0] s;
    casez (s) // synopsys parallel_case
      11'b??????????1:
        _53_ = b[31:0];
      11'b?????????1?:
        _53_ = b[63:32];
      11'b????????1??:
        _53_ = b[95:64];
      11'b???????1???:
        _53_ = b[127:96];
      11'b??????1????:
        _53_ = b[159:128];
      11'b?????1?????:
        _53_ = b[191:160];
      11'b????1??????:
        _53_ = b[223:192];
      11'b???1???????:
        _53_ = b[255:224];
      11'b??1????????:
        _53_ = b[287:256];
      11'b?1?????????:
        _53_ = b[319:288];
      11'b1??????????:
        _53_ = b[351:320];
      default:
        _53_ = a;
    endcase
  endfunction
  assign _12_ = _53_(32'd3735928559, { ctrl_reg, 29'h00000000, irq_status_reg[0], sensor_valid, 1'h0, sensor0_data, sensor1_data, sensor2_data, 29'h00000000, irq_status_reg[2:0], irq_mask_reg, irq_thresh0_reg, irq_thresh1_reg, irq_thresh2_reg, pwr_ctrl_reg }, { _22_, _21_, _20_, _19_, _18_, _10_, _17_, _16_, _15_, _14_, _13_ });
  assign _10_ = reg_addr == 8'h14;
  assign _18_ = reg_addr == 8'h10;
  assign _19_ = reg_addr == 8'h0c;
  assign _20_ = reg_addr == 8'h08;
  assign _21_ = reg_addr == 8'h04;
  assign _02_ = reg_rd_en ? _12_ : 32'd0;
  assign _13_ = reg_addr == 8'h28;
  assign _14_ = reg_addr == 8'h24;
  assign _15_ = reg_addr == 8'h20;
  assign _16_ = reg_addr == 8'h1c;
  assign _17_ = reg_addr == 8'h18;
  assign _22_ = ! reg_addr;
  assign _23_ = irq_sensor2 ? 1'h1 : irq_status_reg[2];
  assign _24_ = reg_wdata[2] ? 1'h0 : _23_;
  assign _00_[2] = _11_ ? _24_ : _23_;
  assign _25_ = irq_sensor1 ? 1'h1 : irq_status_reg[1];
  assign _26_ = reg_wdata[1] ? 1'h0 : _25_;
  assign _00_[1] = _11_ ? _26_ : _25_;
  assign _27_ = irq_sensor0 ? 1'h1 : irq_status_reg[0];
  assign _28_ = reg_wdata[0] ? 1'h0 : _27_;
  assign _00_[0] = _11_ ? _28_ : _27_;
  assign _29_ = | _03_;
  assign _00_[31:3] = 29'h00000000;
  assign irq_status_reg[31:3] = 29'h00000000;
  assign pwr_ctrl_mode = pwr_ctrl_reg[2:1];
  assign pwr_ctrl_sleep_req = pwr_ctrl_reg[0];
endmodule

module vega_top(clk, rst_n, ext_wakeup_in, rtc_wakeup_in, irq_wakeup_in, ext_wakeup_en, rtc_wakeup_en, irq_wakeup_en, thermal_alert, battery_low, fault_in, psel, penable, pwrite, paddr, pwdata, prdata, pready, pslverr, reg_wr_en, reg_rd_en
, reg_addr, reg_wdata, reg_rdata, reg_ack, sensor0_data, sensor1_data, sensor2_data, pmu_active, pmu_sleeping, pmu_fault, pmu_state_out, irq_out, wakeup_src_status);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input ext_wakeup_in;
  wire ext_wakeup_in;
  input rtc_wakeup_in;
  wire rtc_wakeup_in;
  input irq_wakeup_in;
  wire irq_wakeup_in;
  input ext_wakeup_en;
  wire ext_wakeup_en;
  input rtc_wakeup_en;
  wire rtc_wakeup_en;
  input irq_wakeup_en;
  wire irq_wakeup_en;
  input thermal_alert;
  wire thermal_alert;
  input battery_low;
  wire battery_low;
  input fault_in;
  wire fault_in;
  input psel;
  wire psel;
  input penable;
  wire penable;
  input pwrite;
  wire pwrite;
  input [7:0] paddr;
  wire [7:0] paddr;
  input [31:0] pwdata;
  wire [31:0] pwdata;
  output [31:0] prdata;
  wire [31:0] prdata;
  output pready;
  wire pready;
  output pslverr;
  wire pslverr;
  input reg_wr_en;
  wire reg_wr_en;
  input reg_rd_en;
  wire reg_rd_en;
  input [7:0] reg_addr;
  wire [7:0] reg_addr;
  input [31:0] reg_wdata;
  wire [31:0] reg_wdata;
  output [31:0] reg_rdata;
  wire [31:0] reg_rdata;
  output reg_ack;
  wire reg_ack;
  input [31:0] sensor0_data;
  wire [31:0] sensor0_data;
  input [31:0] sensor1_data;
  wire [31:0] sensor1_data;
  input [31:0] sensor2_data;
  wire [31:0] sensor2_data;
  output pmu_active;
  wire pmu_active;
  output pmu_sleeping;
  wire pmu_sleeping;
  output pmu_fault;
  wire pmu_fault;
  output [3:0] pmu_state_out;
  wire [3:0] pmu_state_out;
  output irq_out;
  wire irq_out;
  output [2:0] wakeup_src_status;
  wire [2:0] wakeup_src_status;
  wire _0_;
  wire clk_gate_en;
  wire clk_proc;
  wire context_saved;
  wire context_valid;
  wire iso_en;
  wire lvl_shift_en;
  wire proc_idle;
  wire proc_irq_ack;
  wire proc_irq_in;
  wire [1:0] pwr_ctrl_mode;
  wire pwr_ctrl_sleep_req;
  wire pwr_sw_off;
  wire ret_restore_done;
  wire ret_restore_en;
  wire ret_save_done;
  wire ret_save_en;
  wire seq_sleep_ack;
  wire seq_sleep_cmd;
  wire seq_wakeup_ack;
  wire seq_wakeup_cmd;
  wire sleep_req;
  wire wakeup_clear;
  wire wakeup_req;
  assign _0_ = ~ clk_gate_en;
  \$paramod$75c960d2b8780f31b5b2a9710a4ae3f10fb177d0\data_processor  u_data_processor (
    .clk(clk_proc),
    .clk_gate_en(clk_gate_en),
    .irq_ack(proc_irq_ack),
    .irq_in(irq_out),
    .paddr(paddr),
    .penable(penable),
    .prdata(prdata),
    .pready(pready),
    .proc_idle(proc_idle),
    .psel(psel),
    .pslverr(pslverr),
    .pwdata(pwdata),
    .pwrite(pwrite),
    .rst_n(rst_n)
  );
  icg_cell u_icg_proc (
    .clk_in(clk),
    .clk_out(clk_proc),
    .enable(_0_),
    .test_en(1'h0)
  );
  \$paramod$aa0e0fe2fcccd29e4fd4c43da721521782bc64cd\pmu_fsm  u_pmu_fsm (
    .battery_low(battery_low),
    .clk(clk),
    .fault_in(fault_in),
    .mem_idle(1'h1),
    .pmu_active(pmu_active),
    .pmu_fault(pmu_fault),
    .pmu_sleeping(pmu_sleeping),
    .pmu_state_out(pmu_state_out),
    .proc_idle(proc_idle),
    .rst_n(rst_n),
    .seq_sleep_ack(seq_sleep_ack),
    .seq_sleep_cmd(seq_sleep_cmd),
    .seq_wakeup_ack(seq_wakeup_ack),
    .seq_wakeup_cmd(seq_wakeup_cmd),
    .sleep_req(pwr_ctrl_sleep_req),
    .thermal_alert(thermal_alert),
    .wakeup_req(wakeup_req)
  );
  power_sequencer u_power_sequencer (
    .clk(clk),
    .clk_gate_en(clk_gate_en),
    .iso_en(iso_en),
    .lvl_shift_en(lvl_shift_en),
    .pwr_sw_off(pwr_sw_off),
    .ret_restore_done(ret_restore_done),
    .ret_restore_en(ret_restore_en),
    .ret_save_done(ret_save_done),
    .ret_save_en(ret_save_en),
    .rst_n(rst_n),
    .seq_sleep_ack(seq_sleep_ack),
    .seq_sleep_cmd(seq_sleep_cmd),
    .seq_wakeup_ack(seq_wakeup_ack),
    .seq_wakeup_cmd(seq_wakeup_cmd)
  );
  retention_ctrl u_retention_ctrl (
    .clk(clk),
    .context_saved(context_saved),
    .context_valid(context_valid),
    .ret_restore_done(ret_restore_done),
    .ret_restore_en(ret_restore_en),
    .ret_save_done(ret_save_done),
    .ret_save_en(ret_save_en),
    .rst_n(rst_n)
  );
  sensor_regbank u_sensor_regbank (
    .clk(clk),
    .irq_out(irq_out),
    .pwr_ctrl_mode(pwr_ctrl_mode),
    .pwr_ctrl_sleep_req(pwr_ctrl_sleep_req),
    .reg_ack(reg_ack),
    .reg_addr(reg_addr),
    .reg_rd_en(reg_rd_en),
    .reg_rdata(reg_rdata),
    .reg_wdata(reg_wdata),
    .reg_wr_en(reg_wr_en),
    .rst_n(rst_n),
    .sensor0_data(sensor0_data),
    .sensor1_data(sensor1_data),
    .sensor2_data(sensor2_data)
  );
  wakeup_ctrl u_wakeup_ctrl (
    .clk(clk),
    .ext_wakeup_en(ext_wakeup_en),
    .ext_wakeup_in(ext_wakeup_in),
    .irq_wakeup_en(irq_wakeup_en),
    .irq_wakeup_in(irq_wakeup_in),
    .rst_n(rst_n),
    .rtc_wakeup_en(rtc_wakeup_en),
    .rtc_wakeup_in(rtc_wakeup_in),
    .wakeup_clear(pmu_active),
    .wakeup_req(wakeup_req),
    .wakeup_src_status(wakeup_src_status)
  );
  assign sleep_req = pwr_ctrl_sleep_req;
  assign proc_irq_in = irq_out;
  assign wakeup_clear = pmu_active;
endmodule

module wakeup_ctrl(clk, rst_n, ext_wakeup_in, rtc_wakeup_in, irq_wakeup_in, ext_wakeup_en, rtc_wakeup_en, irq_wakeup_en, wakeup_clear, wakeup_req, wakeup_src_status);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input ext_wakeup_in;
  wire ext_wakeup_in;
  input rtc_wakeup_in;
  wire rtc_wakeup_in;
  input irq_wakeup_in;
  wire irq_wakeup_in;
  input ext_wakeup_en;
  wire ext_wakeup_en;
  input rtc_wakeup_en;
  wire rtc_wakeup_en;
  input irq_wakeup_en;
  wire irq_wakeup_en;
  input wakeup_clear;
  wire wakeup_clear;
  output wakeup_req;
  wire wakeup_req;
  output [2:0] wakeup_src_status;
  wire [2:0] wakeup_src_status;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire ext_edge;
  reg ext_prev;
  reg ext_sync_0;
  reg ext_sync_1;
  wire irq_edge;
  reg irq_prev;
  reg irq_sync_0;
  reg irq_sync_1;
  wire rtc_edge;
  reg rtc_prev;
  reg rtc_sync_0;
  reg rtc_sync_1;
  reg wakeup_ext_lat;
  reg wakeup_irq_lat;
  reg wakeup_rtc_lat;
  assign ext_edge = ext_sync_1 & _09_;
  assign rtc_edge = rtc_sync_1 & _10_;
  assign irq_edge = irq_sync_1 & _11_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wakeup_ext_lat <= 1'h0;
    else if (_03_) wakeup_ext_lat <= _00_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wakeup_rtc_lat <= 1'h0;
    else if (_04_) wakeup_rtc_lat <= _02_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) wakeup_irq_lat <= 1'h0;
    else if (_05_) wakeup_irq_lat <= _01_;
  assign _03_ = | { _06_, wakeup_clear };
  assign _04_ = | { _07_, wakeup_clear };
  assign _05_ = | { _08_, wakeup_clear };
  assign _06_ = ext_edge && ext_wakeup_en;
  assign _07_ = rtc_edge && rtc_wakeup_en;
  assign _08_ = irq_edge && irq_wakeup_en;
  assign _09_ = ~ ext_prev;
  assign _10_ = ~ rtc_prev;
  assign _11_ = ~ irq_prev;
  assign _12_ = wakeup_ext_lat | wakeup_rtc_lat;
  assign wakeup_req = _12_ | wakeup_irq_lat;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ext_prev <= 1'h0;
    else ext_prev <= ext_sync_1;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rtc_prev <= 1'h0;
    else rtc_prev <= rtc_sync_1;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) irq_prev <= 1'h0;
    else irq_prev <= irq_sync_1;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ext_sync_0 <= 1'h0;
    else ext_sync_0 <= ext_wakeup_in;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) ext_sync_1 <= 1'h0;
    else ext_sync_1 <= ext_sync_0;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rtc_sync_0 <= 1'h0;
    else rtc_sync_0 <= rtc_wakeup_in;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) rtc_sync_1 <= 1'h0;
    else rtc_sync_1 <= rtc_sync_0;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) irq_sync_0 <= 1'h0;
    else irq_sync_0 <= irq_wakeup_in;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) irq_sync_1 <= 1'h0;
    else irq_sync_1 <= irq_sync_0;
  assign _13_ = _08_ ? 1'h1 : 1'hx;
  assign _01_ = wakeup_clear ? 1'h0 : _13_;
  assign _14_ = _07_ ? 1'h1 : 1'hx;
  assign _02_ = wakeup_clear ? 1'h0 : _14_;
  assign _15_ = _06_ ? 1'h1 : 1'hx;
  assign _00_ = wakeup_clear ? 1'h0 : _15_;
  assign wakeup_src_status = { wakeup_ext_lat, wakeup_rtc_lat, wakeup_irq_lat };
endmodule
