// DESCRIPTION: Generated by verilator_includer via makefile
#define VL_INCLUDE_OPT include
#include "Vtb_vega_top.cpp"
#include "Vtb_vega_top___024root__DepSet_h9af3653c__0.cpp"
#include "Vtb_vega_top___024root__DepSet_he8f56e15__0.cpp"
#include "Vtb_vega_top__main.cpp"
#include "Vtb_vega_top__Trace__0.cpp"
#include "Vtb_vega_top__ConstPool_0.cpp"
#include "Vtb_vega_top___024root__Slow.cpp"
#include "Vtb_vega_top___024root__DepSet_h9af3653c__0__Slow.cpp"
#include "Vtb_vega_top___024root__DepSet_he8f56e15__0__Slow.cpp"
#include "Vtb_vega_top__Syms.cpp"
#include "Vtb_vega_top__Trace__0__Slow.cpp"
